### ISSUE TITLE
Implement support for internal loadbalancer type

### ISSUE THREAD

**Issue by b3zn0gim** [yandex-cloud/cloudapi#7]
This is just a feature request (enhancement) for yandex cloudapi that we would like to see. 

It would be great to have possibility to create Internal network load balancers. As far as I see in `yandex/cloud/loadbalancer/v1/network_load_balancer.proto`, someone suggested that internal balancer type will be introduced in the future:
```
  // Type of the load balancer. Only external load balancers are currently available.
  enum Type {
    TYPE_UNSPECIFIED = 0;

    // External network load balancer.
    EXTERNAL = 1;

    // Internal network load balancer.
    INTERNAL = 2;
  }
```

If you wonder if anyone is looking for this feature, we are here and glad to discuss implementation

**Comment by alex-vlasov-l1** [comment]
Hey!  We already have internal load balancer in preview -  it is fully supported in YC/TF/API but since it's not yet in General availability phase - there are some limitations etc.  Please open a support ticket (https://console.cloud.yandex.com/support)  and we will activate internal lb feature for your account, and will share with you methods to deploy internal balancer with YC/TF/K8S.
